# Generated by Django 5.1.5 on 2025-02-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_options_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('draft', 'Draft')], default='active', max_length=10),
        ),
    ]
